version: "3"
networks:
  romanovkv-my-netology-hw:
    driver: bridge
    ipam:
      config:
      - subnet: 172.22.0.0/24

services:
  netology-db:
    image: postgres:latest
    container_name: romanovkv-netology-db
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: {{pass}}
      POSTGRES_DB: romanovkv-db
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      romanovkv-my-netology-hw:
        ipv4_address: 172.22.0.2
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: romanovkv-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: romanovkv@ilove-netology.com
      PGADMIN_DEFAULT_PASSWORD: 1q2w3e
    ports:
      - "61231:80"
    networks:
      romanovkv-my-netology-hw:
        ipv4_address: 172.22.0.3
    restart: always
    depends_on:
      - netology-db



  zabbix-server:
    image: zabbix/zabbix-server-pgsql
    links:
      - netology-db
    container_name: romanovkv-zabbix-netology
    environment:
      DB_SERVER_HOST: '172.22.0.2'
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: {{pass}}
    ports:
      - "10051:10051"
    networks:
      romanovkv-my-netology-hw:
        ipv4_address: 172.22.0.4
    restart: always
    depends_on:
      - netology-db

  zabbix_wgui:
    image: zabbix/zabbix-web-apache-pgsql
    links:
      - netology-db
      - zabbix-server
    container_name: romanovkv-netology-zabbix-frontend
    environment:
      DB_SERVER_HOST: '172.22.0.2'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: {{pass}}
      ZBX_SERVER_HOST: "zabbix_wgui"
      PHP_TZ: "Europe/Moscow"
    ports:
      - "80:8080"
      - "443:8443"
    networks:
      romanovkv-my-netology-hw:
        ipv4_address: 172.22.0.5
    restart: always
    depends_on:
      - netology-db
      - zabbix-server
